language: java
jdk:
- oraclejdk8
env:
  global:
  - TERM=dumb 
  - JAVA_LIBRARY_PATH=/usr/lib/jni
  - secure: Da9Brv5WKCE3z0bp5u52X1Rqul5C/r7idGj/yLhHnlEvHXPDQHaGXEQw4fNhRkB586lx6xilO8sra2FHoLDMKsqwE0h2+NKsrHQepTSFOR/fp/otoA/kiBue23ZfhsAEFn/uliVU36xLkt+LsyVqSKa+9JKDA5z1hXSemXGGVGw=
before_install:
- wget -N https://downloads.gradle.org/distributions/gradle-2.2.1-bin.zip
- unzip gradle-2.2.1-bin.zip
- export PATH=`pwd`/gradle-2.2.1/bin:$PATH
- sudo apt-get install -y --force-yes hdfview
# Added from hellbender public
- sudo mkdir -p /usr/local/lib/R/
- sudo mkdir -p site-library
- ln -sFv ~/site-library /usr/local/lib/R/site-library
- apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E084DAB9
- add-apt-repository "deb http://cran.rstudio.com/bin/linux/ubuntu precise/"
- apt-get update
- apt-get install -y r-base-dev=3.1.3-1precise2
- apt-get install -y --force-yes r-base-core=3.1.3-1precise2
- Rscript scripts/install_R_packages.R
after_success:
- gradle jacocoTestReport coveralls
